SET(CTEST_PROJECT_NAME GridConversion)
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")
SET(CTEST_DROP_SITE_CDASH TRUE)

IF(NOT DEFINED CTEST_DROP_METHOD)
  SET(CTEST_DROP_METHOD "http")
ENDIF(NOT DEFINED CTEST_DROP_METHOD)

#ADD_SUBDIRECTORY(IRAD)

IF(CTEST_DROP_METHOD STREQUAL "http")
  SET(CTEST_DROP_SITE "irweb")
  SET(CTEST_DROP_LOCATION "/cdash/submit.php?project=GridConversion")
ENDIF(CTEST_DROP_METHOD STREQUAL "http")
  