SET(CTEST_PROJECT_NAME Rocstar-public)
SET(CTEST_NIGHTLY_START_TIME "02:00:00 EST")
SET(CTEST_DROP_SITE_CDASH TRUE)

IF(NOT DEFINED CTEST_DROP_METHOD)
  SET(CTEST_DROP_METHOD "http")
ENDIF(NOT DEFINED CTEST_DROP_METHOD)

IF(CTEST_DROP_METHOD STREQUAL "http")
  SET(CTEST_DROP_SITE "irweb")
  SET(CTEST_DROP_LOCATION "/cdash/submit.php?project=Rocstar-public")
ENDIF(CTEST_DROP_METHOD STREQUAL "http")
