      program prog
!      open(7,file='motor_13.txt')
!      do
!        read(7,*,iostat=ios) time, psi
!        if (ios /= 0) exit
!        write(*,*) time, psi*6895
!      enddo
!
! Open file hep.txt, generated by script extract_hep.
! Shift the time to line up the peak with the lab scale 
! rocket M13 data.  Write to standard out.
!
      implicit none
      integer nmax,i,ios,ip,imax
      parameter(nmax=5000)
      real p(nmax),time(nmax)
      real pmax,t_offset

      data t_offset /0.30/

      pmax = 0.
      imax = 0
      open(7,file='hep.txt',status='old')
      do i=1,nmax
        read(7,*,iostat=ios) time(i), p(i)
        if (ios /= 0) exit
        if (p(i) > pmax) then
          pmax = p(i)
          imax = i
        endif
!        time(i) = time(i)*1.0e-06 ! Convert from microseconds
      enddo
      ip = i-1
      do i=1,ip
!        write(*,*) time(i)-time(imax)+t_offset, p(i)
        write(*,*) time(i)+t_offset, p(i)
      enddo
      end
