//
//  Copyright@2013, Illinois Rocstar LLC. All rights reserved.
//
//  See LICENSE file included with this source or
//  (opensource.org/licenses/NCSA) for license information.
//

#include <unistd.h>
#include <algorithm>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "gtest/gtest.h"

char **ARGV;
int ARGC;

int main(int argc, char *argv[]) {
  ::testing::InitGoogleTest(&argc, argv);
  ARGC = argc;
  ARGV = argv;
  return RUN_ALL_TESTS();
}

TEST(ACM_Rocflu, Script) {
  // Enter necessary filename variables here
  std::string sourceDir = ARGV[1];
  std::string buildDir = ARGV[2];
  std::string mpiExec = ARGV[3];
  std::string mpiNumProcFlag = ARGV[4];
  std::string InputDir("ACM_RocfluTest");

  std::string text;
  // Remove old test InputDir if present
  system("pwd");
  text =
    "if [ -d " + InputDir + " ] ; then \n"
    "echo \"removing " + InputDir + " directory\" ; \n"
    "rm -r " + InputDir + " ; \n"
    "fi \n";
  system(text.c_str());

  // Make InputDir directory to run test in
  text.clear();
  text = "mkdir " + InputDir;
  system(text.c_str());
  text.clear();

  // Move into ACM_RocfluTest directory
  text = buildDir + "/testing/" + InputDir;
  chdir(text.c_str());

  // Copy input data into InputDir
  text.clear();
  text = "cp -r " + sourceDir +
    "/testing/share/Testing/test_data/ACM_Rocflu/* .";
  system(text.c_str());

  // Run executable to generate output data
  text.clear();
  text =
    buildDir + "/bin/rocprep "
               "-A "
               "-b "
               "-m "
               "-u "
               "1 1 "
               "-n 4 "
               "-d ./ACM_data "
               "-t ./ACM_4 \n";
  system(text.c_str());

  text.clear();
  chdir("./ACM_4");

  // Rocstar run executable
  text = mpiExec + " " + mpiNumProcFlag + " 4 " + buildDir + "/bin/rocstar";

  system(text.c_str());

  chdir("..");
  // Compare the output generated by this test run with the gold standard
  std::ifstream fCheck("ACM.prb_0001_check");
  std::ifstream fCompare("ACM_4/Rocflu/Modout/ACM.prb_0001");
  double checkNum, compareNum, aggregateError = 0.0;
  while (!fCheck.eof()) {
    fCheck >> checkNum;
    fCompare >> compareNum;
    EXPECT_EQ(checkNum, compareNum)
        << "The calculated value and the gold-standard differ!!" << std::endl;
    ASSERT_LT(std::abs(compareNum - checkNum), 1e-10);
    aggregateError += std::abs(compareNum - checkNum);
    ASSERT_LT(aggregateError, 1e-10);
    // this check catches if the output file was not generated, or the file
    // is of a different length than the gold standard
    if ((fCheck.eof() && !fCompare.eof()) || (!fCheck.eof() && fCompare.eof())) {
      FAIL() << "One of the output files is larger than the other!\n"
             << "This likely means that the setup is incorrect." << std::endl;
    }
  }
}
