FROM centos:7

RUN yum update -y
RUN yum upgrade -y

# Compilers and build tools.
RUN yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
RUN yum groupinstall "Development Tools" -y
RUN yum install cmake3 make mpich-3.2-devel.x86_64 cgnslib-devel -y
RUN yum install hdf5-devel hdf-devel.x86_64 blas-devel lapack-devel environment-modules -y
RUN yum install vim -y

# Finds the module command, loads the mpich module
RUN echo "source /etc/profile.d/modules.sh" >> /etc/skel/.bashrc
RUN echo "module load mpi/mpich-3.2-x86_64" >> /etc/skel/.bashrc

# Copy the TPLs ( metis-4 & IMPACT )
COPY . /home/

# Install IMPACT
RUN yum install /home/IMPACT-2.1.0-Linux.rpm -y

# Create a user so that the pipeline does not run as root
ENV BASH_ENV "/etc/skel/.bashrc"
RUN useradd -U --shell /bin/bash -m -k /etc/skel -d /home/user -u 35553 -c "Build Account" build
USER build

WORKDIR /rocstar/
ENTRYPOINT /bin/bash
