FROM ubuntu:18.04

RUN apt update -y
RUN apt upgrade -y

WORKDIR /rocstar/
# ENTRYPOINT /home/

# Compilers and build tools.
RUN apt install g++-7 gfortran-7 gcc-7 cmake libmpich-dev libcgns-dev libhdf5-dev libhdf4-dev liblapack-dev perl -y

RUN apt install vim -y
RUN apt install wget gnupg software-properties-common -y

RUN sh -c "wget -O - http://nemosys-repository.illinois.rocstar/nemosys-repository-pub.gpg | apt-key add -"
RUN add-apt-repository "deb http://nemosys-repository.illinois.rocstar/ bionic main"
RUN apt-get update

# RUN echo $(ls -la)

# Install IMPACT and metis4
RUN apt install impact metis4 -y
