FROM ubuntu:16.04

RUN apt update -y
RUN apt upgrade -y

WORKDIR /rocstar/
# ENTRYPOINT /home/

# Compilers and build tools.
RUN apt install g++-5 gfortran-5 gcc-5 cmake mpich libcgns-dev libhdf5-dev libhdf4-dev liblapack-dev perl -y

RUN apt install vim -y

# Copy the TPLs ( metis-4 & IMPACT )
COPY . /home/
# RUN echo $(ls -la)

RUN apt install /home/IMPACT-2.1.0-Linux.deb -y
