/* Generated by Together */

#ifndef HEXELEMENT_H
#define HEXELEMENT_H

#include "Element.hpp"

class HexElement : public Element {
public:

  HexElement();

  HexElement(Node ** thenodes);

  ~HexElement();

  virtual int getNumNodes() const;
  virtual int getNumFaces() const;

protected:

  virtual void setFaceFromNodes(int num, Node** nodes);

  virtual void setFromMyNodes();

};


#endif //HEXELEMENT_H
