/* Generated by Together */

#ifndef QCOELEMENT_H
#define QCOELEMENT_H

#include "Element.hpp"

class QCoElement : public Element {
public:

  QCoElement();

  QCoElement(Node ** thenodes);

  ~QCoElement();

  virtual int getNumNodes() const;
  virtual int getNumFaces() const;

  virtual void replaceFaceNode (Node *node, Node *new_node, Face* face );

protected:

  virtual void setFaceFromNodes(int num, Node** nodes);

  virtual void setFromMyNodes();

};


#endif //QCOELEMENT_H
