/* Generated by Together */

#ifndef QUADFACE_H
#define QUADFACE_H
#include "Face.hpp"
class Node;


class QuadFace : public Face {

public:    

    /**
     * Builds the QuadFace object from an array of four nodes.  The element(s) must be set
     * later with the setElement methods. 
     */
    QuadFace(Node * * theNodes);
    
    QuadFace();

    /**
     * Destructor. 
     */
    ~QuadFace();

    /**
     * Returns the number of nodes for this type of face (four for the quad face) 
     */
    virtual int getNumNodes() const;    



    virtual Element* buildCohesive( Element* side_elem, Node* node, 
				    Node* new_node );

};

#endif //QUADFACE_H
