/* Generated by Together */

#ifndef TCOELEMENT_H
#define TCOELEMENT_H

#include "Element.hpp"

class TCoElement : public Element {
public:

  TCoElement();

  TCoElement(Node ** thenodes);

  ~TCoElement();

  virtual int getNumNodes() const;
  virtual int getNumFaces() const;

  virtual void replaceFaceNode (Node *node, Node *new_node,  Face* face );

protected:

  virtual void setFaceFromNodes(int num, Node** nodes);

  virtual void setFromMyNodes();

};


#endif //TCOELEMENT_H
