/* Generated by Together */

#ifndef TETELEMENT_H
#define TETELEMENT_H

#include "Element.hpp"
#include <assert.h>

class TetElement : public Element {
public:

  TetElement();

  TetElement(Node ** thenodes);

  ~TetElement();

  virtual int getNumNodes() const;
  virtual int getNumFaces() const;

protected:

  virtual void setFaceFromNodes(int num, Node** nodes);

  virtual void setFromMyNodes();
  virtual double getMinEdgeLength();

};


#endif //TETELEMENT_H
