/* Generated by Together */

#ifndef TRIFACE_H
#define TRIFACE_H
#include "Face.hpp"
class Node;

class TriFace : public Face {
public:    

    /**
     * Builds the TriFace object from an array of three nodes.  The element(s) must be set
     * later with the setElement methods. 
     */
    TriFace(Node * * theNodes);
    
    TriFace() ;

    /**
     * Destructor. 
     */
    ~TriFace();

    /**
     * Returns the number of nodes for this type of face (three for the
     * triangular face). 
     */
    virtual int getNumNodes() const;    

    virtual Element* buildCohesive( Element* side_elem, Node* node, 
				    Node* new_node );

};
#endif //TRIFACE_H
