/* Generated by Together */

#include "TriFace.hpp"
#include "TCoElement.hpp"

TriFace::TriFace(Node * * theNodes):
  Face( e_tri )
{
  d_nodes = new Node*[3];
  int i;
  for( i = 0; i < 3; i++ ){
    d_nodes[i] = theNodes[i];
    d_nodes[i]->addFace( this );
  }
}

TriFace::TriFace() {
  d_nodes = new Node*[3];
  int i;
  for (i=0; i<3; i++) d_nodes[i]=0;
}

TriFace::~TriFace(){
  int i;
  for( i = 0; i < 3; i++ ){
    d_nodes[i]->removeFace( this );
  }
}

int TriFace::getNumNodes() const
{ return 3; }


Element* TriFace::buildCohesive( Element* side_elem, Node* node, 
				 Node* new_node ){

  int ind=-1;
  int i;
  for( i = 0; i < 3; i++ ){
    if( d_nodes[i] == node ){
      ind = i;
      break;
    }
  }
  Element* coelem;

  Node* new_nodes[6];
  
  //the order of the second three nodes looks wrong - need to assess and 
  //correct if so.  Order should be 1,2,3, and 4,5,6 with 4 corresponding to 
  //3 and not to 1. 
  
  //Note:  when a cohesive element is made, it always has two doubled node
  //numbers:  when do they get updated?
  
  if( d_E1 == side_elem ){ // normal to side
    new_nodes[0] = d_nodes[0];
    new_nodes[1] = d_nodes[1];
    new_nodes[2] = d_nodes[2];
    new_nodes[3] = (ind == 0 ? new_node : d_nodes[0] );
    new_nodes[4] = (ind == 1 ? new_node : d_nodes[1] );
    new_nodes[5] = (ind == 2 ? new_node : d_nodes[2] );
    d_E1 = d_E2;
    d_E2 = 0;
    coelem = new TCoElement( new_nodes );
    // now for this face set E1 to  the coelem
    d_E2 = d_E1; 
    d_E1 = coelem;
    Face* oface = coelem->getFaces()[1];
    ((TriFace*)oface)->d_E2 = side_elem;
    side_elem->replaceFace( this, oface );
  }
  else { // normal to the other side
    d_E2 = 0; 
    new_nodes[0] = (ind == 0 ? new_node : d_nodes[0] );
    new_nodes[1] = (ind == 1 ? new_node : d_nodes[1] );
    new_nodes[2] = (ind == 2 ? new_node : d_nodes[2] );
    new_nodes[3] = d_nodes[0];
    new_nodes[4] = d_nodes[1];
    new_nodes[5] = d_nodes[2];
    coelem = new TCoElement( new_nodes );
    // now for the new face set E2 to side_elem (will correct the nodes later)
    Face* oface = coelem->getFaces()[0];
    ((TriFace*)oface)->d_E2 = side_elem;
    side_elem->replaceFace( this, oface );
  }
  return coelem;
}
  
